POST https://anyrouter.top/api/user/sign_in
Content-Type: application/json
New-Api-User: 3542
Referer: https://anyrouter.top/console/topup
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
Cookie: session=MTc1NzkwMjU2MnxEWDhFQVFMX2dBQUJFQUVRQUFEXzRQLUFBQWNHYzNSeWFXNW5EQW9BQ0hWelpYSnVZVzFsQm5OMGNtbHVad3dOQUF0bmFYUm9kV0pmTXpVME1nWnpkSEpwYm1jTUJnQUVjbTlzWlFOcGJuUUVBZ0FDQm5OMGNtbHVad3dJQUFaemRHRjBkWE1EYVc1MEJBSUFBZ1p6ZEhKcGJtY01Cd0FGWjNKdmRYQUdjM1J5YVc1bkRBa0FCMlJsWm1GMWJIUUdjM1J5YVc1bkRBVUFBMkZtWmdaemRISnBibWNNQmdBRU5WRTJhd1p6ZEhKcGJtY01EUUFMYjJGMWRHaGZjM1JoZEdVR2MzUnlhVzVuREE0QURFWnJhRzUxV0hKUFpEYzNWQVp6ZEhKcGJtY01CQUFDYVdRRGFXNTBCQVFBX2h1c3xmn7eu_CSts6oC_dyvrsMo5gtQvd9E4X3Ol0p72_97Mw==; acw_tc=a3b552d217594099776154678e56dd3d5820375e439b9580aece0d3b65; cdn_sec_tc=a3b552d217594099776154678e56dd3d5820375e439b9580aece0d3b65; acw_sc__v2=68de7739d32beafa0be4bef9a24cf99866c5350f